---
- name: Install Homebrew
  command: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew
  when: ansible_os_family == "Darwin"

- name: Add taps
  homebrew_tap: "tap={{ item }} state=present"
  with_items: "{{ homebrew_taps }}"

- name: Install homebrew packages
  homebrew: "name={{ item }} state=present"
  with_items: "{{ homebrew_packages }}"

- name: Install cask applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir={{ homebrew_cask_dir }}"
  with_items: "{{ homebrew_cask_apps }}"
